version: '3.4'

services:
  pmtdb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGateway/Dockerfile

volumes:
  mongo_data:
